spring.application.name=my-film-app

server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/filmapp
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
